### ISSUE TITLE
Social Login Not Working After Deployment Update

### ISSUE THREAD

**Issue by IndyJones72** [driftyco/ionic-cloud#38]
The new social stuff is AMAZING and works well...until I deploy an update.  Steps to reproduce:

Login to either Facebook or Twitter Successfully
Check for Updates
Download Update
Extract Update
Logout
Try to click Facebook of Twitter Login again
-- OR --
Completely terminate app on the device and relaunch and click on Facebook or Twitter Login

Here's how I logout a user (notice how I'm clearing the cache) 

```
$scope.LogoutUser = function() {
            console.log("Logging Out User");

            $timeout(function () {
                $ionicAuth.logout();
                $ionicHistory.clearCache();
                $ionicHistory.clearHistory();
                $scope.LoggedIn = false;
                $state.go("signin", { "ActionName": "LoggedOut"});

            },300)

        }

```

Here's my code for the update (perhaps that's where the problem occurs?)

```
$scope.hasUpdate = false;
    $scope.NoUpdates = false;

    var deploy = $ionicDeploy;

    // Check Ionic Deploy for new code
    $scope.checkForUpdates = function () {

        $ionicLoading.show({ template: 'Checking for Updates...', delay: 400 });

        $scope.NoUpdates = false;
        console.log('Ionic Deploy: Checking for updates');
        deploy.check().then(function (hasUpdate) {
            console.log('Ionic Deploy: Update available: ' + hasUpdate);
            if(hasUpdate) {
                $timeout(function(){
                    $ionicLoading.hide();
                    $scope.NoUpdates = false;
                },2000);
                $scope.doUpdate();
            }
            else {
                console.log("No Updates Available");
                $timeout(function(){
                    $ionicLoading.hide();
                    $scope.NoUpdates = true;
                },2000);

            }

        }, function (err) {
            console.error('Ionic Deploy: Unable to check for updates', err);
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
        });
    }

    // Update app code with new release from Ionic Deploy
    $scope.doUpdate = function () {

        $ionicLoading.show({ template: 'Downloading Updates...', delay: 400 });
        console.log("Starting Update...");
        deploy.download().then(function (res) {
            console.log('Ionic Deploy: Download Success! ', res);

            $timeout(function(){
                $ionicLoading.hide();
            },2000);
            $scope.doExtract();

        }, function (err) {
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
            console.log('Ionic Deploy: Update error! ', err);
        }, function (prog) {
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
            console.log('Ionic Deploy: Progress... ', prog);
        });
    };
    
    // Extract the Code so it will be updated on the App next time its launched
    $scope.doExtract = function () {
        console.log("Starting Extraction...");

        $ionicLoading.show({ template: 'Applying Updates...', delay: 400 });
        deploy.extract().then(function (res) {
            console.log('Ionic Deploy: Extraction Success! ', res);
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
        }, function (err) {
            console.log('Ionic Deploy: Extraction error! ', err);
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
        }, function (prog) {
            console.log('Ionic Deploy: Extraction Progress... ', prog);
            $timeout(function(){
                $ionicLoading.hide();
            },2000);
        });
    };

```

and here's the login for FB (the twitter one is the same thing, just with "Twitter" in it)

```
$scope.FacebookLogin = function () {
        $ionicAuth.login('facebook').then(function (_info) {

            $ionicUser.details.username = $ionicUser.social.facebook.data.full_name;
            $ionicUser.details.email = $ionicUser.social.facebook.data.email;
            $ionicUser.details.image = $ionicUser.social.facebook.data.raw_data.picture.data.url;
            $ionicUser.save();

            $scope.loginSuccess();
        }, function () {
            $scope.signupFailure(_info);
        });
    };
```

Facebook does not give me any errors of any kind on the console or network side, but Twitter does have that damn missing cordova browser thing coming up again.

Any thoughts?

**Comment by dwieeb** [comment]
I'm not seeing any such failure following those steps. Are you testing this on Android or iOS? 

- Is `signupFailure()` being called, which would mean the login is failing for some reason? 
- Progress is no longer tracked as the third parameter of the `then` function and judging from the copy/paste, I don't think they're being called in your code.
- What are all those `$timeout`s for?
- You mentioned the "missing cordova browser" message. Can you elaborate?

**Comment by IndyJones72** [comment]
@dwieeb - Thanks for commenting.  

-iOS so far.
-The signupFailure seems to be called on the Twitter one, but not the Facebook one. 
-Only on the one (the Twitter failure) do we get the "InApp Browser Plugin Missing)
-Only on a complete reinstallation via Xcode after a new build and then run/install does the app allow me to log in via social networks again.
-Those timeouts are because for some reason, without them, the ionicLoading will not show or disappear.

My thoughts and I could be completely wrong here....in the deployment the login status or something else is being lost.  If you're not seeing it with following these steps, it must be something on my side here.

**Comment by IndyJones72** [comment]
Ok I know what's going on, but not sure why.  The deployment for some reason, when extracted/installed the cordova.js file is now missing.  It's there on the initial ionic emulate iOS or ionic build iOS and then installed via xCode on the actual device. 

When the updates are downloaded and extracted, everything seems to be loaded properly except the cordova.js file.   Any ideas?

**Comment by dwieeb** [comment]
@IndyJones72 You have `cordova.js` uncommented in your `index.html`, right?

**Comment by IndyJones72** [comment]
Yep. That's what's so puzzling. I've even tried doing a build iOS first before doing the ionic upload and nothing. 

I know we don't have access however there's no way for you to check on one of our latest uploads to see if the Cordova.js file is in there is there?

**Comment by dwieeb** [comment]
You should be able to remote debug with Safari, right? 

@Fuiste, any ideas? 

@IndyJones72 The `$timeout`s shouldn't be necessary with the latest release. If you update your cloud client, you should be able to take those out. The problem is related to angular change detection, which should have been fixed [in this commit](https://github.com/driftyco/ionic-cloud/commit/68d55d3ed72dc540ed9dd9f16d06bd85ab0fa0c2).

**Comment by IndyJones72** [comment]
@dwieeb @Fuiste -  Yes, I have the debugger running in safari and see the Cordova file there. While keeping the debugger up I do the update. Suddenly the new files are there except for the Cordova.js one. 

If you recall I had performed the migration and had not uncommented the Cordova file. So it's almost as if something still doesn't think that needs to be part of the upload or something is happening in the extraction.

**Comment by Fuiste** [comment]
@IndyJones72 which version of the deploy plugin are you running?

**Comment by IndyJones72** [comment]
@Fuiste - I feel like an idiot and clearly haven't had enough coffee this morning.  How do you find out which version of the deploy plugin I'm running?

**Comment by Fuiste** [comment]
No worries @IndyJones72!  You can find your plugin versions with:

```bash
ionic plugin list
```

The current version of Deploy should be 0.6.2

**Comment by IndyJones72** [comment]
@dwieeb - I see...with regards to the angular change detection.  Was this the commit that went out in the latest NPM which included the added social information?  In doing a npm list I see I'm running @ionic/cloud@0.8.0-beta.14.

**Comment by IndyJones72** [comment]
@Fuiste - Thanks buddy.  Ok here's the list:

```
DOUGs-MacBook-Pro:DAEATW_20160817 dougjustice$ ionic plugin list
cordova-plugin-admobpro 2.18.0 "AdMob Plugin Pro"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
ionic-plugin-deploy 0.6.2 "IonicDeploy"
phonegap-plugin-push 1.8.1 "PushPlugin"
```

...and I did confirm the issue is definitely with the deploy.  To recap very quickly....the cordova.js file exists when I run 

`ionic serve`
`ionic emulate iOS`
`ionic build iOS` (and then run it via xCode on my device.

If I upload/deploy, and I attempt to run the latest version on Ionic View...it fails due to the missing cordova.js file as well.  Is there anyway to do a deploy locally to confirm the JS file is not being included?  Is there something missing in one of my xml config files that may need to be manually added so it knows to add the cordova.js plugin?

**Comment by Fuiste** [comment]
@IndyJones72 what's your app ID?

**Comment by IndyJones72** [comment]
@Fuiste - It's a9fe9f50

**Comment by IndyJones72** [comment]
@Fuiste / @dwieeb - Just pinging back to see if you have any thoughts on this.  I'm unfortunately dead in the water until I can get this working and the Food & Wine Fest starts on September 14, so I have a little bit of time to make this a part of the app.  

I did create another app on Ionic Cloud and copied in the code, changed the app id and did the relink, and the same thing occurs.  The "mocked" Cordova.js appears in the **ionic serve**.....the actual cordova.js exists when doing a **ionic build iOS** and running from an actual device, and it's also there for the **simulator** as well.  It's just during an ionic upload it seems to not want to be there as in Ionic View it will also not work.

After developing for over 25 years I certainly know this could be something I fudged up on my side, but I don't quite know what else to try at this point.  Thanks as always!

**Comment by IndyJones72** [comment]
SUCCESS!!!!! - @Fuiste / @dwieeb - Not sure if you guys did anything but it works!!!  If you did something great!!!  In the meantime I created a new app completely from scratch (an empty ionic app) and followed your new docs to the letter and the social logins worked before and after the deploy.

I then went back into my a9fe9f50 app and the only thing I changed was I added the immediate $ionicDeploy.load(); since I saw that in your new docs and thought that was a great idea.

So if you did find something, please let me know as I'd hate to think I wasted everyone's time by simply adding the load() command, but let me know your thoughts.

p.s.  Great job on the new docs...they look great and very well written.

**Comment by Fuiste** [comment]
Glad to hear you got it working @IndyJones72!  We were still looking into things on our end and hadn't come up with anything, so it's good to see you got it resolved!

Thanks for the kind words on the new docs as well, we are really excited to finally get them in front of people, as the old ones definitely needed some love!
